#!/bin/sh

setup_eth0_interface() {
    ip addr add 192.168.1.100/24 dev eth0
    ip link set dev eth0 up
}

setup_ftp_folder() {
    mkdir -p /home/ftp/upload
    chown ftp:ftp /home/ftp/upload
    chown root:root /home/ftp
}

main() {
    setup_eth0_interface
    setup_ftp_folder
}

main "$@"